[[http]]
name = "hk01-influxdb-relay"
bind-addr = "0.0.0.0:5888"
output = [
    { name="hk", location = "http://127.0.0.1:8086/write",timeout = "60s", buffer-size-mb = 200, max-batch-kb = 2048, max-delay-interval = "5s" },
    { name="hw", location = "http://192.168.10.2:8086/write",timeout = "60s", buffer-size-mb = 200, max-batch-kb = 2048, max-delay-interval = "5s" },
    { name="jl", location = "http://jldb.wangy.buzz/write",timeout = "60s", buffer-size-mb = 200, max-batch-kb = 2048, max-delay-interval = "5s" },
]
